### PR TITLE
Add area folder

### PR DESCRIPTION
**Pull request by totahuanocotl**

### CODE REVIEW

**Review by ltoconauhatot — COMMENTED** [review]
What is this?

**Review by ltoconauhatot — APPROVED** [review]

**Review by ltoconauhatot — CHANGES_REQUESTED** [review]
not really

**Review by sqtiami — DISMISSED** [review]
I say yes

**Review by ltoconauhatot — DISMISSED** [review]
finme then

**Review by imaitqs — DISMISSED** [review]
bot approves

**Review by sqtiami — APPROVED** [review]
Ok!

**Review by ltoconauhatot — COMMENTED** [review]
don't know!

**Pull request closed without merging**
